shop/cart/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^shopAdmin/category/create/$',
        AdminCategoryCreateView.as_view(), name="adminCategoryCreate"),
    url(r'^shopAdmin/category/(?P<pk>\d+)/update/$',
        AdminCategoryUpdateView.as_view(), name="adminCategoryUpdate"),
    url(r'^shopAdmin/category/list/$',
        AdminCategoryListView.as_view(), name="adminCategoryList"),


    url(r'^shopAdmin/coupon/create/$',
        AdminCouponCreateView.as_view(), name="adminCouponCreate"),
    url(r'^shopAdmin/coupon/list/$',
        AdminCouponListView.as_view(), name="adminCouponList"),
    url(r'^shopAdmin/coupon/(?P<pk>\d+)/update/$',
        AdminCouponUpdateView.as_view(), name='adminCouponUpdate'),
    url(r'^shopAdmin/coupon/(?P<pk>\d+)/update/$',
        AdminCouponUpdateView.as_view(), name='adminCouponUpdate'),

    url(r'^shopAdmin/product/create/$',
        AdminProductCreateView.as_view(), name="adminProductCreate"),

    url(r'^shopAdmin/siteconfig/create/$',
        AdminSiteConfigCreateView.as_view(), name="adminSiteConfigCreate"),
    url(r'^shopAdmin/siteconfig/list/$',
        AdminSiteConfigListView.as_view(), name="adminSiteConfigList"),
    url(r'^shopAdmin/siteconfig/(?P<pk>\d+)/update/$',
        AdminSiteConfigUpdateView.as_view(), name="adminSiteConfigUpdate"),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include('messaging.urls', namespace='message')),
    url(r'', include('account.urls', namespace='account')),
    url(r'', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Timestampable(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Photo(Timestampable):
    photo = models.ImageField("Photo")
    title = models.CharField(
        "Photo Title", max_length=255, null=True, blank=True)

    def __str__(self):
        if self.title:
            return self.title
        return self.photo.url


class Category(Timestampable):
    title = models.CharField("Category Title", max_length=255)
    slug = models.SlugField("Category Slug", unique=True)
    description = models.TextField(
        "Category Description", null=True, blank=True)
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title


class Tag(Timestampable):
    title = models.CharField("Tag Title", max_length=255, unique=True)
    description = models.TextField(
        "Category Description", null=True, blank=True)

    def __str__(self):
        return self.title


class Product(Timestampable):
    name = models.CharField("Product Name", max_length=512)
    slug = models.SlugField("Product Slug", unique=True)
    photos = models.ManyToManyField(Photo)
    description = models.TextField("Product Description")
    visibility = models.BooleanField("Product Visibility", default=True)
    reference_code = models.CharField(
        "Product Reference Code", max_length=128, null=True, blank=True)
    barcode = models.CharField(
        "Product Barcode", max_length=128, null=True, blank=True)
    quantity = models.PositiveIntegerField("Produc Quantity", default=0)
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)
    old_price = models.FloatField("Product Price", default=0)
    price = models.FloatField("Product Price", default=0)
    vat = models.FloatField("VAT", default=13)
    vat_included = models.BooleanField("VAT Inclusive", default=False)
    discount_percent = models.FloatField(
        "Discount Percentage", default=0)
    discount_amount = models.FloatField("Discount Percentage", default=0)

    def __str__(self):
        return self.name


class ProductInTransaction(Timestampable):
    products = models.OneToOneField(Product, null=True, blank=True)
    quantity = models.PositiveIntegerField("Product Quantity", default=0)

    def __str__(self):
        return self.product.name


class Cart(Timestampable):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ForeignKey(ProductInTransaction, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Wishlist(Timestampable):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ForeignKey(ProductInTransaction, null=True, blank=True)

    def __str__(self):
        return self.user.username


DISCUNT_CHOICES = (
    (1, "Percentage"),
    (2, "Flat")
)


class Coupon(Timestampable):
    title = models.CharField("Coupon Title", max_length=255)
    code = models.CharField("Coupon Code", max_length=255)
    valid_from = models.DateTimeField("Valid From")
    valid_to = models.DateTimeField("Valid To")
    validity_count = models.PositiveIntegerField(
        "Validity Count", null=True, blank=True, default=1)
    discount_type = models.PositiveIntegerField(
        "Discount Type", choices=DISCUNT_CHOICES, default=1)
    discount_percent = models.FloatField("Discount Percentage", default=0)
    discount_amount = models.FloatField("Discount Amount", default=0)

    def __str__(self):
        return self.title


class Point(Timestampable):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_point = models.PositiveIntegerField("Total Points", default=0)

    def __str__(self):
        return self.user.username


class Order(Timestampable):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ForeignKey(ProductInTransaction, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Featured(Timestampable):
    products = models.ForeignKey(Product, null=True, blank=True)

    def __str__(self):
        return self.products.title


class Slider(Timestampable):
    title = models.TextField("Slider Title")
    photos = models.ForeignKey(Photo, null=True, blank=True)

    def __str__(self):
        return self.title


class SiteConfig(Timestampable):
    key = models.CharField("Site Config Key", max_length=255)
    value = models.TextField("Site Config Value")

    def __str__(self):
        return self.key

shop/cart/forms.py
from django import forms
from .models import *


class CouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = [
            "title",
            "code",
            "valid_from",
            "valid_to",
            "validity_count",
            "discount_type",
            "discount_percent",
            "discount_amount",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})
        self.fields['discount_type'].widget.attrs.update({'id': 'select-list'})
        self.fields['valid_from'].widget.attrs.update(
            {'class': 'datetimepicker form-control'})
        self.fields['valid_to'].widget.attrs.update(
            {'class': 'datetimepicker form-control'})


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "title",
            "parent",
            "description",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})
        self.fields['parent'].widget.attrs.update({'id': 'select-list'})
        self.fields['description'].widget.attrs.update({'id': 'summernote'})


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "reference_code",
            "barcode",
            "visibility",
            "photos",
            "description",
            "quantity",
            "categories",
            "tags",
            "price",
            "vat",
            "vat_included",
            "discount_percent",
            "discount_amount",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'id': 'summernote'})
        self.fields['categories'].widget.attrs.update({'id': 'select-list'})
        self.fields['tags'].widget.attrs.update({'data-role': 'tagsinput'})


class SiteConfigForm(forms.ModelForm):
    class Meta:
        model = SiteConfig
        fields = [
            "key",
            "value",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})

shop/cart/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView, UpdateView
from django.utils.text import slugify
from django.contrib import messages
from .models import *
from .forms import *

# Create your views here


def getDateTime(datetime):
    date, time, meridiem = datetime.split(" ")
    hour, minute = time.split(":")
    if meridiem == "PM":
        hr = int(hour) + 12
        hr %= 24
        hour = str(hr)
    time = hour + ':' + minute
    datetime = date + ' ' + time
    return datetime


class AdminCouponCreateView(SuccessMessageMixin, CreateView):
    model = Coupon
    template_name = 'cart/adminCouponCreate.html'
    form_class = CouponForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Coupon Successfully Added"

    def form_valid(self, form, **kwargs):
        couponObjects = Coupon.objects.filter(code=form.instance.code)
        if couponObjects:
            messages.error(self.request, "Coupon Code Already Exist!!!")
            return redirect('cart:adminCouponCreate')
        else:
            form.instance.valid_from = getDateTime(
                form.cleaned_data.get('validFrom'))
            form.instance.valid_to = getDateTime(
                form.cleaned_data.get('validTo'))
            form.save()

        return super(AdminCouponCreateView, self).form_valid(form, *kwargs)


class AdminCouponUpdateView(SuccessMessageMixin, UpdateView):
    model = Coupon
    template_name = 'cart/adminCouponUpdate.html'
    form_class = CouponForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Coupon Successfully Updated"

    def form_valid(self, form, **kwargs):
        couponObjects = Coupon.objects.filter(code=form.instance.code)
        if couponObjects:
            messages.error(self.request, "Coupon Code Already Exist!!!")
            return redirect('cart:adminCouponCreate')
        else:
            form.instance.valid_from = getDateTime(
                form.cleaned_data.get('validFrom'))
            form.instance.valid_to = getDateTime(
                form.cleaned_data.get('validTo'))
            form.save()

        return super(AdminCouponCreateView, self).form_valid(form, *kwargs)


class AdminCouponListView(ListView):
    model = Coupon
    template_name = 'cart/adminCouponList.html'
    context_object_name = 'coupons'

    def get_queryset(self):
        return Coupon.objects.filter(deleted_at=None)


class AdminCategoryCreateView(SuccessMessageMixin, CreateView):
    model = Category
    template_name = 'cart/adminCategoryCreate.html'
    form_class = CategoryForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Category Successfully Added"

    def form_valid(self, form, **kwargs):
        categoryObjects = Category.objects.filter(slug=form.instance.title)
        if not categoryObjects:
            form.instance.slug = slugify(form.instance.title)
            form.save()
        else:
            messages.error(self.request, "Category Already Exist!!!")
            return redirect('cart:adminCategoryCreate')

        return super(AdminCategoryCreateView, self).form_valid(form, *kwargs)


class AdminCategoryUpdateView(SuccessMessageMixin, UpdateView):
    model = Category
    template_name = 'cart/adminCategoryUpdate.html'
    form_class = CategoryForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Category Successfully Updated"

    def form_valid(self, form, **kwargs):
        categoryObjects = Category.objects.filter(slug=form.instance.title)
        if not categoryObjects:
            form.instance.slug = slugify(form.instance.title)
            form.save()
        else:
            messages.error(self.request, "Category Already Exist!!!")
            return redirect('cart:adminCategoryCreate')

        return super(AdminCategoryCreateView, self).form_valid(form, *kwargs)


class AdminCategoryListView(ListView):
    model = Category
    template_name = 'cart/adminCategoryList.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.filter(deleted_at=None)


class AdminProductCreateView(SuccessMessageMixin, CreateView):
    model = Product
    template_name = 'cart/adminProductCreate.html'
    form_class = ProductForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Product Successfully Added"


class AdminSiteConfigCreateView(SuccessMessageMixin, CreateView):
    model = SiteConfig
    template_name = 'cart/adminSiteConfigCreate.html'
    form_class = SiteConfigForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Site Config Successfully Added"


class AdminSiteConfigUpdateView(SuccessMessageMixin, UpdateView):
    model = SiteConfig
    template_name = 'cart/adminSiteConfigUpdate.html'
    form_class = SiteConfigForm
    success_url = reverse_lazy("message:adminMessage")
    success_message = "Site Config Successfully Updated"


class AdminSiteConfigListView(ListView):
    model = SiteConfig
    template_name = 'cart/adminSiteConfigList.html'
    context_object_name = 'siteConfigs'

    def get_queryset(self):
        return SiteConfig.objects.filter(deleted_at=None)

shop/templates/cart/adminCategoryCreate.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
{{block.super}} | Category Create
{% endblock %}


{% block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs//summernote/summernote.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/select2/select2.css' %}" />
{% endblock %}

{% block content %}
<section>
    <div class="section-header">
        <ol class="breadcrumb">
            <li>Dashboard</li>
            <li class="active">Category Create</li>
        </ol>
    </div>

    <div class="section-body contain-lg">
        <!-- BEGIN BASIC ELEMENTS -->
        <form class="form" role="form" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                        <div class="form-group">
                            {{form.title}}
                            <label for="{{ form.title.id_for_label }}">Category Title</label>
                        </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                        <div class="form-group">
                            {{form.parent}}
                            <label for="{{ form.parent.id_for_label }}">Parent Category</label>
                        </div>
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.description.id_for_label }}">Description</label>
                            <br>
                            {{form.description}}
                        </div>
                        <div class="col-xs-12 text-right">
                            <button class="btn ink-reaction btn-primary btn-raised" type="submit">Create</button>
                        </div><!--end .col -->
                    </div><!--end .card-body -->
                </div><!--end .card -->

            </div><!--end .col -->
        </div><!--end .row -->
        </form>
    </div><!--end .section-body -->
</section>

{% endblock %}

{% block extra_js%}
<script src="{% static 'assets/js/libs/summernote/summernote.min.js' %}"></script>
<script src="{% static 'assets/js/libs/select2/select2.min.js' %}"></script>

<script type="text/javascript">
    $('#category').addClass('active')
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $('#select-list').select2();
        $('#summernote').summernote({
            height:200,
            toolbar: [
                ['style', ['style']],
                ['fontstyle', ['bold', 'italic', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']]
            ]
        });
    });
</script>
{% endblock %}

shop/templates/cart/adminCategoryUpdate.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
{{block.super}} | Category Update
{% endblock %}


{% block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs//summernote/summernote.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/select2/select2.css' %}" />
{% endblock %}

{% block content %}
<section>
    <div class="section-header">
        <ol class="breadcrumb">
            <li>Dashboard</li>
            <li class="active">Category Update</li>
        </ol>
    </div>

    <div class="section-body contain-lg">
        <h2>Cagtegory Update</h2>
        <!-- BEGIN BASIC ELEMENTS -->
        <form class="form" role="form" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                        <div class="form-group">
                            {{form.title}}
                            <label for="{{ form.title.id_for_label }}">Category Title</label>
                        </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                        <div class="form-group">
                            {{form.parent}}
                            <label for="{{ form.parent.id_for_label }}">Parent Category</label>
                        </div>
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.description.id_for_label }}">Description</label>
                            <br>
                            {{form.description}}
                        </div>
                        <div class="col-xs-12 text-right">
                            <button class="btn ink-reaction btn-primary btn-raised" type="submit">Update</button>
                        </div><!--end .col -->
                    </div><!--end .card-body -->
                </div><!--end .card -->

            </div><!--end .col -->
        </div><!--end .row -->
        </form>
    </div><!--end .section-body -->
</section>

{% endblock %}

{% block extra_js%}
<script src="{% static 'assets/js/libs/summernote/summernote.min.js' %}"></script>
<script src="{% static 'assets/js/libs/select2/select2.min.js' %}"></script>

<script type="text/javascript">
    $('#category').addClass('active')
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $('#select-list').select2();
        $('#summernote').summernote({
            height:200,
            toolbar: [
                ['style', ['style']],
                ['fontstyle', ['bold', 'italic', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']]
            ]
        });
    });
</script>
{% endblock %}

shop/templates/cart/adminCouponList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | Coupon List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-header">
    <ol class="breadcrumb">
        <li>Dashboard</li>
        <li class="active">Coupon List</li>
    </ol>
</div>
<div class="section-body">
<h2>Coupon List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'cart:adminCouponCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-alpha">Title</th>
                                    <th class="sort-alpha">Code</th>
                                    <th class="sort-alpha">Valid From</th>
                                    <th class="sort-alpha" >Valid To</th>
                                    <th class="sort-numeric" >Validity Count</th>
                                    <th class="sort-alpha" >Discount Type</th>
                                    <th class="sort-numeric" >Discount Percent</th>
                                    <th class="sort-numeric" >Discount Amount</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for coupon in coupons %}
                                <tr>
                                    <td>{{coupon.title}}</td>
                                    <td>{{coupon.code}}</td>
                                    <td>{{coupon.valid_from}}</td>
                                    <td>{{coupon.valid_to}}</td>
                                    <td>{{coupon.validity_count}}</td>
                                    <td>{{coupon.get_discount_type_display}}</td>
                                    <td>{{coupon.discount_percent}} %</td>
                                    <td>Rs. {{coupon.discount_amount}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm">Action</button>
                                            <button type="button" class="btn dropdown-toggle btn-sm" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                <li><a href="{% url 'cart:adminCouponUpdate' coupon.id %}" ><i class="fa fa-edit"></i> Edit</a></li>
                                                <li><a><i class="fa fa-trash"></i> Delete</a></li>
                                            </ul>
                                        </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#coupon').addClass('active')
</script>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}

shop/templates/cart/adminSiteConfigList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{block.super}} | SiteConfig List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-header">
    <ol class="breadcrumb">
        <li>Dashboard</li>
        <li class="active">Site Config List</li>
    </ol>
</div>
<div class="section-body">
<h2>Site Config List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'cart:adminCouponCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-alpha">Key</th>
                                    <th class="sort-alpha">Value</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for siteConfig in siteConfigs %}
                                <tr>
                                    <td>{{siteConfig.key}}</td>
                                    <td>{{siteConfig.value}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm">Action</button>
                                            <button type="button" class="btn dropdown-toggle btn-sm" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                <li><a href="{% url 'cart:adminSiteConfigUpdate' siteConfig.id %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                <li><a><i class="fa fa-trash"></i> Delete</a></li>
                                            </ul>
                                        </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#coupon').addClass('active')
</script>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}